### ISSUE TITLE
Please create the v3 release

### ISSUE THREAD

**Issue by spaze** [symfonycorp/security-checker-action#6]
Please create the v3 release. There's a v3 tag here https://github.com/symfonycorp/security-checker-action/releases/tag/v3 but only v2 release.

This is why the GitHub Actions page offers v2 only
https://github.com/marketplace/actions/the-php-security-checker
![Screenshot_20220901-185218](https://user-images.githubusercontent.com/1966648/187969664-667000ce-0596-4e5d-b762-6415c15c7b92.png)

V2 stopped working for me due to a missing symfonycorp/cli Docker image.

**Comment by fabpot** [comment]
Fixed now. We had a tag but not a release.

**Comment by janbarasek** [comment]
Same issue here:

![Snímek obrazovky 2022-09-07 v 12 58 02](https://user-images.githubusercontent.com/4738758/188862100-7bad3636-b512-4a33-88c5-ae48fb38e6d9.png)
